# SAC agent configuration for the reach cube task

# Training parameters
n_epochs: 150
n_steps: 4000
n_steps_test: 2000
use_cluster: true
save_model: true
model_name: "reach_cube_agent"

#Reward parameters
contact_cost_weight: -1e-4
control_cost_weight: -1e-4
cube_distance_weight: 1.0
cube_touched_reward: 10.0
contact_threshold: 2.0